[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends lld",
]

[build.env]
passthrough = ["ELF_LOADER_CI=1"]

[target.riscv64gc-unknown-none-elf]
image = "ghcr.io/cross-rs/riscv64gc-unknown-linux-gnu:main"

[target.aarch64-unknown-none]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-none]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
